site_name: Waveform User Manual
site_url: https://tracktion.github.io/waveform_manual/
docs_dir: docs
site_dir: site

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
